export async function sendReviewEmail(email: string, name: string, review: string, rating: number) {
  console.log(`[v0] ========== NEW REVIEW NOTIFICATION ==========`)
  console.log(`[v0] Name: ${name}`)
  console.log(`[v0] Email: ${email}`)
  console.log(`[v0] Rating: ${rating} stars`)
  console.log(`[v0] Review: ${review}`)
  console.log(`[v0] `)
  console.log(`[v0] Email Template Sent:`)
  console.log(`[v0] Subject: Thank you for your review, ${name}!`)
  console.log(`[v0] `)
  console.log(`[v0] Dear ${name},`)
  console.log(`[v0] `)
  console.log(`[v0] Thank you so much for taking the time to review Shree Dental Clinic!`)
  console.log(`[v0] Your ${rating}-star review means a lot to us.`)
  console.log(`[v0] `)
  console.log(`[v0] To help others discover our services, we kindly request you to also`)
  console.log(`[v0] post your review on Google Maps. It only takes a minute!`)
  console.log(`[v0] `)
  console.log(`[v0] Click here to post on Google Maps:`)
  console.log(`[v0] https://maps.app.goo.gl/AsZ19tucWvQJxFzo8`)
  console.log(`[v0] `)
  console.log(`[v0] Thank you for choosing Shree Dental Clinic!`)
  console.log(`[v0] `)
  console.log(`[v0] Best regards,`)
  console.log(`[v0] Dr. Chanchal Rani`)
  console.log(`[v0] Shree Dental Clinic`)
  console.log(`[v0] =============================================`)
}
